<?php

namespace AppBundle\Repository;

/**
 * CategoryOddsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryOddsRepository extends \Doctrine\ORM\EntityRepository
{
}
