<?php

namespace AppBundle\Repository;

use Symfony\Component\HttpFoundation\Request;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCountryBySportIdAction(Request $request)
    {
        $em = $this->getEntityManager();
        $idSport = $request->get("id_sport");

        $query = $em->createQuery(
            'SELECT c
            FROM AppBundle:Country c where c.sport = ' . $idSport . ' order by c.name ASC'
        );
        return $query->getArrayResult();
    }

}
