<?php

namespace AppBundle\Repository;

use Symfony\Component\HttpFoundation\Request;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEventByLeagueAction(Request $request)
    {//idLeague en param

        $em = $this->getEntityManager();
        $idLeague = $request->get("id");

        $query = $em->createQuery(
            'SELECT e
        FROM AppBundle:Event e where e.league = ' . $idLeague . ' order by e.eventTime ASC'
        );
        return $query->getArrayResult();
    }
}
