<?php

namespace AppBundle\Repository;

use Symfony\Component\HttpFoundation\Request;

/**
 * LeagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeagueRepository extends \Doctrine\ORM\EntityRepository
{

    public function getleagueByCountryIdAction(Request $request)
    {
        $em = $this->getEntityManager();
        $idCountry = $request->get("id_country");
        $qb = $em->createQueryBuilder();
        $qb->select('u')
            ->from('AppBundle:League', 'u')
            ->where('u.country ='. $idCountry)
            ->orderBy('u.name',"ASC");
        return $qb->getQuery()->getResult();

    }

}
