<?php

namespace AppBundle\Repository;

/**
 * OddRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OddRepository extends \Doctrine\ORM\EntityRepository
{
}
