<?php

namespace AppBundle\Repository;

/**
 * SousCategoryOddsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategoryOddsRepository extends \Doctrine\ORM\EntityRepository
{
}
